[DOC] Minor updates to software paper for JOSS review
Living-with-machines/MapReader pull request #446
Opened 2024-06-22 20:01 UTC by emdupre

### Summary

Relates to https://github.com/openjournals/joss-reviews/issues/6434

### Describe your changes

Minor updates to the software paper accompanying the JOSS submission for MapReader for readability and formatting. 

### Checklist before assigning a reviewer (update as needed)

- [ ] Self-review code
- [ ] Ensure submission passes current tests
- [ ] Add tests
- [ ] Update relevant docs

### Reviewer checklist

Please add anything you want reviewers to specifically focus/comment on.

- [ ] Everything looks ok?

2024-07-02 08:57 UTC, kmcdono2 requested changes

2024-07-02 08:57 UTC, kmcdono2 commented on paper/paper.md
> +MapReader's approach was inspired by methods in biomedical imaging and adapted for use by historians, and it is suitable for a wide range of applications in image analysis: it has, for example, been
I prefer to leave this in the original form

2024-07-02 08:57 UTC, kmcdono2 commented on paper/paper.md
> +MapReader is among the first end-to-end pipelines for processing historical maps and other images that are designed to lower barriers to experimenting with computer vision in answering research quest
I am going to make an amendment in the paper to update the final sentence. (I will do this outside of this review.)

2024-08-02 10:22 UTC, kallewesterling commented
@kmcdono2 @rwood-97 Is this the PR that's blocking the JOSS paper from going through?

2024-08-05 20:18 UTC, emdupre commented
Apologies, I hadn't realized I didn't push the reversion on the suggested rephrasing.

I've also incorporated the update to the unpublished Corcoran reference.

2024-08-06 13:19 UTC, rwood-97 approved these changes

2024-08-06 13:22 UTC, merged