Replace most `assert` statements with more descriptive`raise` statements
Living-with-machines/MapReader pull request #476
Opened 2024-08-02 11:38 UTC by kallewesterling

### Summary

The `AssertionError` output isn't the most user-friendly response from software. In this PR, I've changed most of them into more helpful error messages. I'll also see if I can add tests for the exceptions, wherever I can manage to generate them.

Fixes #475

### Describe your changes

Describe changes/updates you have made to the code.

### Checklist before assigning a reviewer (update as needed)

- [ ] Self-review code
- [ ] Ensure submission passes current tests
- [ ] Add tests
- [ ] Update relevant docs

### Reviewer checklist

Please add anything you want reviewers to specifically focus/comment on.

- [ ] Everything looks ok?

2024-08-05 10:45 UTC, rwood-97 commented on mapreader/download/downloader_utils.py
> +        raise ValueError("Zoom level must be positive")
can we ad a test for this

2024-08-05 10:46 UTC, rwood-97 commented on mapreader/classify/load_annotations.py
> +                            f"[ERROR] Label indices do not match label counts. Please check the label indices for label '{input_label}'."
can we add a test for this

2024-08-05 10:47 UTC, rwood-97 commented on mapreader/download/data_structures.py
can we add tests

2024-08-05 10:49 UTC, rwood-97 commented on mapreader/annotate/utils.py
what does this file do? Do we have any docs about it?

2024-08-05 10:51 UTC, rwood-97 commented on mapreader/download/downloader.py
#217 
I need to do this at some point

2024-08-05 10:53 UTC, rwood-97 commented on tests/test_download/test_data_structures.py
its weird that codecov is saying the tests aren't covered by tests (I think just ignore?)

Can we add `test_sheet_downloader.py` to the `test_download` directory?

2024-08-05 10:53 UTC, rwood-97 requested changes
Some comments, mostly just can we add more tests for all of these

2024-08-05 14:28 UTC, kallewesterling commented on mapreader/download/downloader_utils.py
> +        raise ValueError("Zoom level must be positive")
Adding!

2024-08-05 14:49 UTC, kallewesterling commented on mapreader/annotate/utils.py
Looks like the `mapreader.annotate.utils.prepare_annotation` function was used in a workshow in June 2023:

![image](https://github.com/user-attachments/assets/b04d983b-6f5c-440e-8a21-a72f485530ff)

But maybe we do something else now... 🤔  I can't remember... but if we drop this file, we probably should update the notebooks -- or at least add a note... or, perhaps, better: we should make sure that notebooks are always installing an annotated commit from the MapReader repo rather than a general install, which would always bring in a newer version into old notebooks...

2024-08-05 15:32 UTC, rwood-97 commented on mapreader/annotate/utils.py
Okay yes I think this is from the old annotator then and we can probably delete it - potentially in a separate PR though. 

For the workshops in 2023 I have a README to say it has outdated code [here](https://github.com/Living-with-machines/MapReader/blob/main/worked_examples/geospatial/workshop_june_2023/README.md) and in the 2024 ones there is an `assert version = xxx` for checking people are using the corresponding version of the notebooks (e.g. [here](https://github.com/Living-with-machines/MapReader/blob/main/worked_examples/geospatial/workshops_2024/Workshop_2024_part2.ipynb)).

2024-08-08 08:30 UTC, rwood-97 commented on mapreader/annotate/utils.py
#478

2024-08-08 08:30 UTC, rwood-97 approved these changes
lgtm :)

2024-08-08 08:44 UTC, merged